MOCK_DHIS2_COMPLETION_EMPTY_RESPONSE = {}

##########################################
# Responses from DHIS2 version : 2.37.10 #
##########################################
MOCK_DHIS2_COMPLETION_200_IMP_RESPONSE_V2_37 = {
    "responseType": "ImportSummary",
    "status": "SUCCESS",
    "importOptions": {
        "idSchemes": {},
        "dryRun": True,
        "async": False,
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        "reportMode": "FULL",
        "skipExistingCheck": False,
        "sharing": False,
        "skipNotifications": False,
        "skipAudit": False,
        "datasetAllowsPeriods": False,
        "strictPeriods": False,
        "strictDataElements": False,
        "strictCategoryOptionCombos": False,
        "strictAttributeOptionCombos": False,
        "strictOrganisationUnits": False,
        "requireCategoryOptionCombo": False,
        "requireAttributeOptionCombo": False,
        "skipPatternValidation": False,
        "ignoreEmptyCollection": False,
        "force": False,
        "firstRowIsHeader": True,
        "skipLastUpdated": False,
        "mergeDataValues": False,
        "skipCache": False,
    },
    "description": "Import process complete.",
    "importCount": {"imported": 1, "updated": 0, "ignored": 0, "deleted": 0},
    "conflicts": [],
}

MOCK_DHIS2_COMPLETION_200_UPD_RESPONSE_V2_37 = {
    "responseType": "ImportSummary",
    "status": "SUCCESS",
    "importOptions": {
        "idSchemes": {},
        "dryRun": False,
        "async": False,
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        "reportMode": "FULL",
        "skipExistingCheck": False,
        "sharing": False,
        "skipNotifications": False,
        "skipAudit": False,
        "datasetAllowsPeriods": False,
        "strictPeriods": False,
        "strictDataElements": False,
        "strictCategoryOptionCombos": False,
        "strictAttributeOptionCombos": False,
        "strictOrganisationUnits": False,
        "requireCategoryOptionCombo": False,
        "requireAttributeOptionCombo": False,
        "skipPatternValidation": False,
        "ignoreEmptyCollection": False,
        "force": False,
        "firstRowIsHeader": True,
        "skipLastUpdated": False,
        "mergeDataValues": False,
        "skipCache": False,
    },
    "description": "Import process complete.",
    "importCount": {"imported": 0, "updated": 1, "ignored": 0, "deleted": 0},
    "conflicts": [],
}

MOCK_DHIS2_COMPLETION_CONFLICT_409_OU_RESPONSE_V2_37 = {
    "responseType": "ImportSummary",
    "status": "ERROR",
    "importOptions": {
        "idSchemes": {},
        "dryRun": True,
        "async": False,
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        "reportMode": "FULL",
        "skipExistingCheck": False,
        "sharing": False,
        "skipNotifications": False,
        "skipAudit": False,
        "datasetAllowsPeriods": False,
        "strictPeriods": False,
        "strictDataElements": False,
        "strictCategoryOptionCombos": False,
        "strictAttributeOptionCombos": False,
        "strictOrganisationUnits": False,
        "requireCategoryOptionCombo": False,
        "requireAttributeOptionCombo": False,
        "skipPatternValidation": False,
        "ignoreEmptyCollection": False,
        "force": False,
        "firstRowIsHeader": True,
        "skipLastUpdated": False,
        "mergeDataValues": False,
        "skipCache": False,
    },
    "description": "Import process complete.",
    "importCount": {"imported": 0, "updated": 0, "ignored": 1, "deleted": 0},
    "conflicts": [{"object": "WRONG", "value": "Organisation unit not found or not accessible"}],
}

MOCK_DHIS2_COMPLETION_CONFLICT_409_PE_RESPONSE_V2_37 = {
    "responseType": "ImportSummary",
    "status": "ERROR",
    "importOptions": {
        "idSchemes": {},
        "dryRun": True,
        "async": False,
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        "reportMode": "FULL",
        "skipExistingCheck": False,
        "sharing": False,
        "skipNotifications": False,
        "skipAudit": False,
        "datasetAllowsPeriods": False,
        "strictPeriods": False,
        "strictDataElements": False,
        "strictCategoryOptionCombos": False,
        "strictAttributeOptionCombos": False,
        "strictOrganisationUnits": False,
        "requireCategoryOptionCombo": False,
        "requireAttributeOptionCombo": False,
        "skipPatternValidation": False,
        "ignoreEmptyCollection": False,
        "force": False,
        "firstRowIsHeader": True,
        "skipLastUpdated": False,
        "mergeDataValues": False,
        "skipCache": False,
    },
    "description": "Import process complete.",
    "importCount": {"imported": 0, "updated": 0, "ignored": 1, "deleted": 0},
    "conflicts": [{"object": "WRONG", "value": "Period not valid"}],
}

MOCK_DHIS2_COMPLETION_CONFLICT_409_DS_RESPONSE_V2_37 = {
    "responseType": "ImportSummary",
    "status": "ERROR",
    "importOptions": {
        "idSchemes": {},
        "dryRun": True,
        "async": False,
        "importStrategy": "CREATE_AND_UPDATE",
        "mergeMode": "REPLACE",
        "reportMode": "FULL",
        "skipExistingCheck": False,
        "sharing": False,
        "skipNotifications": False,
        "skipAudit": False,
        "datasetAllowsPeriods": False,
        "strictPeriods": False,
        "strictDataElements": False,
        "strictCategoryOptionCombos": False,
        "strictAttributeOptionCombos": False,
        "strictOrganisationUnits": False,
        "requireCategoryOptionCombo": False,
        "requireAttributeOptionCombo": False,
        "skipPatternValidation": False,
        "ignoreEmptyCollection": False,
        "force": False,
        "firstRowIsHeader": True,
        "skipLastUpdated": False,
        "mergeDataValues": False,
        "skipCache": False,
    },
    "description": "Import process complete.",
    "importCount": {"imported": 0, "updated": 0, "ignored": 1, "deleted": 0},
    "conflicts": [{"object": "WRONG", "value": "Data set not found or not accessible"}],
}


##########################################
# Responses from DHIS2 version : 2.40.11 #
##########################################
MOCK_DHIS2_COMPLETION_200_IMP_RESPONSE_V2_40 = {
    "httpStatus": "OK",
    "httpStatusCode": 200,
    "status": "OK",
    "message": "Import was successful.",
    "response": {
        "responseType": "ImportSummary",
        "status": "SUCCESS",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": False,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process complete.",
        "importCount": {"imported": 1, "updated": 0, "ignored": 0, "deleted": 0},
        "conflicts": [],
        "rejectedIndexes": [],
    },
}

MOCK_DHIS2_COMPLETION_200_UPD_RESPONSE_V2_40 = {
    "httpStatus": "OK",
    "httpStatusCode": 200,
    "status": "OK",
    "message": "Import was successful.",
    "response": {
        "responseType": "ImportSummary",
        "status": "SUCCESS",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": False,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process complete.",
        "importCount": {"imported": 0, "updated": 1, "ignored": 0, "deleted": 0},
        "conflicts": [],
        "rejectedIndexes": [],
    },
}

MOCK_DHIS2_COMPLETION_CONFLICT_409_OU_RESPONSE_V2_40 = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "ERROR",
    "message": "An error occurred, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "ERROR",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": False,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process complete.",
        "importCount": {"imported": 0, "updated": 0, "ignored": 1, "deleted": 0},
        "conflicts": [{"object": "WRONG", "value": "Organisation unit not found or not accessible"}],
        "rejectedIndexes": [],
    },
}

MOCK_DHIS2_COMPLETION_CONFLICT_409_PE_RESPONSE_V2_40 = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "ERROR",
    "message": "An error occurred, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "ERROR",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": False,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process complete.",
        "importCount": {"imported": 0, "updated": 0, "ignored": 1, "deleted": 0},
        "conflicts": [{"object": "WRONG", "value": "Period not valid"}],
        "rejectedIndexes": [],
    },
}

MOCK_DHIS2_COMPLETION_CONFLICT_409_DS_RESPONSE_V2_40 = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "ERROR",
    "message": "An error occurred, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "ERROR",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": False,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process complete.",
        "importCount": {"imported": 0, "updated": 0, "ignored": 1, "deleted": 0},
        "conflicts": [{"value": "Data set not found or not accessible"}],
        "rejectedIndexes": [],
    },
}
