import requests


class MockDHIS2Response:
    """Mock class to simulate a response from the DHIS2 API for testing purposes."""

    def __init__(self, json_data, status_code=200):  # noqa: ANN001
        self._json_data = json_data
        self.status_code = status_code

    def json(self) -> dict:  # noqa: D102
        return self._json_data

    def raise_for_status(self):  # noqa: D102
        if not (200 <= self.status_code < 300):
            raise requests.exceptions.HTTPError(f"HTTP {self.status_code}")


MOCK_DHIS2_ERROR_503_RESPONSE = {
    "httpStatus": "Service Unavailable",
    "httpStatusCode": 503,
    "status": "ERROR",
    "message": "Service temporarily unavailable",
}

# Example OK response DHIS2 version: '2.40.9'
MOCK_DHIS2_OK_RESPONSE = {
    "httpStatus": "OK",
    "httpStatusCode": 200,
    "status": "OK",
    "message": "Import was successful.",
    "response": {
        "responseType": "ImportSummary",
        "status": "SUCCESS",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {"imported": 1, "updated": 0, "ignored": 0, "deleted": 0},
        "conflicts": [],
        "rejectedIndexes": [],
        "dataSetComplete": "false",
    },
}

# Example 409 conflict response DHIS2 version: '2.40.9'
MOCK_DHIS2_ERROR_409_RESPONSE_DE = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "WARNING",
    "message": "One more conflicts encountered, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "WARNING",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {
            "imported": 1,
            "updated": 0,
            "ignored": 2,
            "deleted": 0,
        },
        "conflicts": [
            {
                "object": "INVALID_1",
                "objects": {"dataElement": "INVALID_1"},
                "value": "Data element not found or not accessible: `INVALID_1`",
                "errorCode": "E7610",
                "property": "dataElement",
                "indexes": [1],
            },
            {
                "object": "INVALID_2",
                "objects": {"dataElement": "INVALID_2"},
                "value": "Data element not found or not accessible: `INVALID_2`",
                "errorCode": "E7610",
                "property": "dataElement",
                "indexes": [2],
            },
        ],
        "rejectedIndexes": [1, 2],
        "dataSetComplete": "false",
    },
}

# Example 409 conflict response DHIS2 version: '2.40.9'
MOCK_DHIS2_ERROR_409_RESPONSE_ORG_UNITS = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "WARNING",
    "message": "One more conflicts encountered, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "WARNING",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {
            "imported": 1,
            "updated": 0,
            "ignored": 2,
            "deleted": 0,
        },
        "conflicts": [
            {
                "object": "INVALID_1_OU",
                "objects": {"organisationUnit": "INVALID_1_OU"},
                "value": "Organisation unit not found or not accessible: `INVALID_1_OU`",
                "errorCode": "E7612",
                "property": "orgUnit",
                "indexes": [1],
            },
            {
                "object": "INVALID_2_OU",
                "objects": {"organisationUnit": "INVALID_2_OU"},
                "value": "Organisation unit not found or not accessible: `INVALID_2_OU`",
                "errorCode": "E7612",
                "property": "orgUnit",
                "indexes": [2],
            },
        ],
        "rejectedIndexes": [1, 2],
        "dataSetComplete": "false",
    },
}

# Example 409 conflict response DHIS2 version: '2.40.9'
MOCK_DHIS2_ERROR_409_RESPONSE_PERIOD = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "WARNING",
    "message": "One more conflicts encountered, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "WARNING",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {
            "imported": 1,
            "updated": 0,
            "ignored": 2,
            "deleted": 0,
        },
        "conflicts": [
            {
                "object": "INVALID_PERIOD_1",
                "objects": {"period": "INVALID_PERIOD_1"},
                "value": "Period not valid: `INVALID_PERIOD_1`",
                "errorCode": "E7611",
                "property": "period",
                "indexes": [1],
            },
            {
                "object": "INVALID_PERIOD_2",
                "objects": {"period": "INVALID_PERIOD_2"},
                "value": "Period not valid: `INVALID_PERIOD_2`",
                "errorCode": "E7611",
                "property": "period",
                "indexes": [2],
            },
        ],
        "rejectedIndexes": [1, 2],
        "dataSetComplete": "false",
    },
}

# Example 409 conflict response DHIS2 version: '2.40.9'
MOCK_DHIS2_ERROR_409_RESPONSE_COC = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "WARNING",
    "message": "One more conflicts encountered, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "WARNING",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {
            "imported": 1,
            "updated": 0,
            "ignored": 2,
            "deleted": 0,
        },
        "conflicts": [
            {
                "object": "INVALID_COC_1",
                "objects": {"categoryOptionCombo": "INVALID_COC_1"},
                "value": "Category option combo not found or not accessible for writing data: `INVALID_COC_1`",
                "errorCode": "E7613",
                "property": "categoryOptionCombo",
                "indexes": [1],
            },
            {
                "object": "INVALID_COC_2",
                "objects": {"categoryOptionCombo": "INVALID_COC_2"},
                "value": "Category option combo not found or not accessible for writing data: `INVALID_COC_2`",
                "errorCode": "E7613",
                "property": "categoryOptionCombo",
                "indexes": [2],
            },
        ],
        "rejectedIndexes": [1, 2],
        "dataSetComplete": "false",
    },
}

# Example 409 conflict response DHIS2 version: '2.40.9'
MOCK_DHIS2_ERROR_409_RESPONSE_AOC = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "WARNING",
    "message": "One more conflicts encountered, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "WARNING",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {
            "imported": 1,
            "updated": 0,
            "ignored": 2,
            "deleted": 0,
        },
        "conflicts": [
            {
                "object": "INVALID_AOC_1",
                "objects": {"categoryOptionCombo": "INVALID_AOC_1"},
                "value": "Attribute option combo not found or not accessible for writing data: `INVALID_AOC_1`",
                "errorCode": "E7615",
                "property": "attributeOptionCombo",
                "indexes": [1],
            },
            {
                "object": "INVALID_AOC_2",
                "objects": {"categoryOptionCombo": "INVALID_AOC_2"},
                "value": "Attribute option combo not found or not accessible for writing data: `INVALID_AOC_2`",
                "errorCode": "E7615",
                "property": "attributeOptionCombo",
                "indexes": [2],
            },
        ],
        "rejectedIndexes": [1, 2],
        "dataSetComplete": "false",
    },
}

# Example 409 conflict response DHIS2 version: '2.40.9'
MOCK_DHIS2_ERROR_409_RESPONSE_VALUE_FORMAT = {
    "httpStatus": "Conflict",
    "httpStatusCode": 409,
    "status": "WARNING",
    "message": "One more conflicts encountered, please check import summary.",
    "response": {
        "responseType": "ImportSummary",
        "status": "WARNING",
        "importOptions": {
            "idSchemes": {},
            "dryRun": True,
            "preheatCache": True,
            "async": False,
            "importStrategy": "CREATE_AND_UPDATE",
            "mergeMode": "REPLACE",
            "reportMode": "FULL",
            "skipExistingCheck": False,
            "sharing": False,
            "skipNotifications": False,
            "skipAudit": True,
            "datasetAllowsPeriods": False,
            "strictPeriods": False,
            "strictDataElements": False,
            "strictCategoryOptionCombos": False,
            "strictAttributeOptionCombos": False,
            "strictOrganisationUnits": False,
            "strictDataSetApproval": False,
            "strictDataSetLocking": False,
            "strictDataSetInputPeriods": False,
            "requireCategoryOptionCombo": False,
            "requireAttributeOptionCombo": False,
            "skipPatternValidation": False,
            "ignoreEmptyCollection": False,
            "force": False,
            "firstRowIsHeader": True,
            "skipLastUpdated": False,
            "mergeDataValues": False,
            "skipCache": False,
        },
        "description": "Import process completed successfully",
        "importCount": {
            "imported": 2,
            "updated": 0,
            "ignored": 1,
            "deleted": 0,
        },
        "conflicts": [
            {
                "object": "VALID2",
                "objects": {"dataElement": "VALID2", "value": "value_not_numeric"},
                "value": "Value must match value type of data element `VALID2`: `La valeur est non numérique`",
                "errorCode": "E7619",
                "property": "value",
                "indexes": [1],
            }
        ],
        "rejectedIndexes": [1],
        "dataSetComplete": "false",
    },
}
